[07-Mar-21 14:47:39 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:47:40 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:47:51 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:47:52 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 14:48:32 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:48:33 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:50:34 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 26, in query_mgs
    keywords = [filename.split()[0], filename.split()[1]]
IndexError: list index out of range
[07-Mar-21 14:53:25 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:53:26 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:53:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:53:42 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 14:55:01 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:55:02 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:56:04 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:56:05 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:56:05 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 14:56:11 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:56:12 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:56:27 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:56:28 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 14:57:23 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:57:24 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:57:28 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 26, in query_mgs
    keywords = [filename.split()[0], filename.split()[1]]
IndexError: list index out of range
[07-Mar-21 14:59:00 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:59:01 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 14:59:03 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 14:59:04 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 14:59:07 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 26, in query_mgs
    keywords = [filename.split(" ")[0], filename.split(" ")[1]]
IndexError: list index out of range
[07-Mar-21 14:59:10 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 14:59:11 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:00:48 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:00:49 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 15:00:59 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:01:00 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:08:37 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:08:38 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 15:08:43 - ERROR] - pyrogram.dispatcher - copy() got an unexpected keyword argument 'from_chat_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 36, in query_mgs
    reply_to_message_id=message.message_id
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: copy() got an unexpected keyword argument 'from_chat_id'
[07-Mar-21 15:09:23 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:09:24 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:09:28 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:09:29 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 15:09:35 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:09:42 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:10:02 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:10:03 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:10:18 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:10:19 - INFO] - user - @space4renjith  started! 

Send a message in your channel now!!
[07-Mar-21 15:14:07 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:14:08 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:14:11 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:14:12 - INFO] - user - @space4renjith  started!
[07-Mar-21 15:15:08 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:15:09 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:15:12 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:15:13 - INFO] - user - @space4renjith  started!
[07-Mar-21 15:20:29 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:20:34 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:22:00 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:22:01 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:22:40 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:22:41 - INFO] - user - @space4renjith  started!
[07-Mar-21 15:23:54 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:23:54 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:30:04 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:30:05 - INFO] - user - @space4renjith  started!
[07-Mar-21 15:30:23 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:30:29 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:30:35 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 15:30:49 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:30:49 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 15:35:00 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 15:35:01 - INFO] - user - @space4renjith  started!
[07-Mar-21 15:36:30 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 15:36:30 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:01:59 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:02:00 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:02:10 - ERROR] - pyrogram.dispatcher - del_mgs() missing 1 required positional argument: 'message_ids'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
TypeError: del_mgs() missing 1 required positional argument: 'message_ids'
[07-Mar-21 16:08:34 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:08:36 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:08:40 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:08:42 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:09:02 - ERROR] - pyrogram.dispatcher - del_mgs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
TypeError: del_mgs() takes 1 positional argument but 2 were given
[07-Mar-21 16:11:55 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:11:56 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:12:00 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:12:01 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:12:13 - ERROR] - pyrogram.dispatcher - Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for message in client.iter_history(group_id):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/get_history.py", line 90, in get_history
    peer=await self.resolve_peer(chat_id),
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/storage/sqlite_storage.py", line 143, in get_peer_by_id
    (peer_id,)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
[07-Mar-21 16:13:51 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:13:52 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:13:56 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:13:57 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:14:11 - ERROR] - pyrogram.dispatcher - [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for message in client.iter_history(group_id[id]):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/get_history.py", line 99, in get_history
    sleep_threshold=60
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
[07-Mar-21 16:16:43 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:16:44 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:16:49 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:16:50 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:17:08 - ERROR] - pyrogram.dispatcher - del_mgs() takes 0 positional arguments but 2 were given
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
TypeError: del_mgs() takes 0 positional arguments but 2 were given
[07-Mar-21 16:17:52 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:17:52 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:17:55 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:17:57 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:18:07 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for message in Bot.iter_history(group_id[id]):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'chat_id'
[07-Mar-21 16:18:23 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:18:23 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:18:27 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:18:28 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:18:35 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for message in Bot.iter_history(chat_id=group_id[id]):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'self'
[07-Mar-21 16:23:38 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:23:38 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:23:42 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:23:43 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:23:43 - ERROR] - pyrogram.dispatcher - [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in client.iter_history(int(-1001158262259)):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/get_history.py", line 99, in get_history
    sleep_threshold=60
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
[07-Mar-21 16:24:19 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:24:19 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:24:19 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:24:22 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:24:23 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:24:24 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(int(-1001158262259)):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'chat_id'
[07-Mar-21 16:24:39 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:24:40 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:24:43 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:24:44 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:24:48 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(chat_id=int(-1001158262259)):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'self'
[07-Mar-21 16:26:30 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:26:31 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:26:34 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:26:35 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:26:37 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(chat_id=message.chat.id):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'self'
[07-Mar-21 16:27:59 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:27:59 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:28:02 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:28:03 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:28:04 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(message.chat.id):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'chat_id'
[07-Mar-21 16:28:33 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:28:33 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:28:38 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:28:39 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:28:45 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:28:46 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:29:29 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:29:30 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:29:31 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(int(update.chat.id)):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'chat_id'
[07-Mar-21 16:31:47 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:31:47 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:31:48 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:33:18 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:33:19 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:33:25 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(Config.GROUP):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'chat_id'
[07-Mar-21 16:35:15 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:35:16 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:35:18 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:35:20 - ERROR] - pyrogram.dispatcher - iter_history() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(chat_id=Config.GROUP):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: iter_history() missing 1 required positional argument: 'self'
[07-Mar-21 16:35:20 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:36:23 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:36:24 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:36:27 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:36:27 - ERROR] - pyrogram.dispatcher - [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(self=bot, chat_id=Config.GROUP):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/get_history.py", line 99, in get_history
    sleep_threshold=60
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
[07-Mar-21 16:36:28 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:36:54 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:36:55 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:36:59 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:37:00 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:37:03 - ERROR] - pyrogram.dispatcher - get_history() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.iter_history(self=Bot, chat_id=Config.GROUP):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: get_history() missing 1 required positional argument: 'self'
[07-Mar-21 16:37:10 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:37:12 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:38:12 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:38:12 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:38:13 - ERROR] - pyrogram.dispatcher - [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in client.iter_history(chat_id=Config.GROUP):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/get_history.py", line 99, in get_history
    sleep_threshold=60
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
[07-Mar-21 16:48:21 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:48:21 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:48:25 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:48:26 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:48:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:48:42 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:48:47 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:48:48 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:49:02 - ERROR] - pyrogram.dispatcher - [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for user_message in client.iter_history(group):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/iter_history.py", line 85, in iter_history
    reverse=reverse
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/get_history.py", line 99, in get_history
    sleep_threshold=60
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
[07-Mar-21 16:49:08 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:49:10 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:52:12 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:52:14 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:52:19 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:19 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:19 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:54:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:57:10 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:57:11 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:57:13 - ERROR] - pyrogram.dispatcher - del_mgs() takes 0 positional arguments but 2 were given
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
TypeError: del_mgs() takes 0 positional arguments but 2 were given
[07-Mar-21 16:58:02 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:58:02 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:58:05 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:58:06 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:58:09 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for user_message in Bot.USER.iter_history(group_id[id]):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 16:58:55 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:58:57 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 16:59:00 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 16:59:01 - INFO] - user - @space4renjith  started!
[07-Mar-21 16:59:14 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.USER.iter_history(int(group_id[id])):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 16:59:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 16:59:20 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:00:59 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:01:00 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:01:01 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.USER.iter_history(Config.GROUP):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 17:01:38 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:01:39 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:01:44 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:01:45 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.USER.iter_history(Config.GROUP):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 17:01:45 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:02:02 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:02:02 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:02:03 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:02:03 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:02:04 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:02:09 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:02:11 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:02:13 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 19, in del_mgs
    async for user_message in Bot.USER.iter_history(Config.GROUP):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 17:02:15 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:02:15 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:02:16 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:03:07 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:03:08 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:03:14 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for user_message in Bot.USER.iter_history(group):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 17:04:21 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:04:22 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:04:23 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:04:25 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:04:26 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:04:29 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 27, in del_mgs
    await messages.delete()
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/types/messages_and_media/message.py", line 2973, in delete
    chat_id=self.chat.id,
AttributeError: 'NoneType' object has no attribute 'id'
[07-Mar-21 17:05:55 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:05:56 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:06:00 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:06:02 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 20, in del_mgs
    async for user_message in client.USER.iter_history(group):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 17:06:02 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:06:22 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:06:22 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:06:22 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:06:25 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:06:27 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:06:30 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'delete'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 29, in del_mgs
    await media.delete()
AttributeError: 'NoneType' object has no attribute 'delete'
[07-Mar-21 17:06:49 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:06:49 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:06:53 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:06:55 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:06:57 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'delete'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 29, in del_mgs
    await media.delete()
AttributeError: 'NoneType' object has no attribute 'delete'
[07-Mar-21 17:09:03 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:09:03 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:09:03 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:09:07 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:09:08 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:10:15 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 17:10:22 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 17:10:30 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 17:11:16 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 17:11:23 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 17:11:30 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 17:13:41 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:13:41 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:13:44 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:13:44 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:13:44 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:13:44 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:14:07 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:14:08 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:14:16 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'message_id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 28, in del_mgs
    message_ids=media.message_id,
AttributeError: 'NoneType' object has no attribute 'message_id'
[07-Mar-21 17:14:53 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:14:54 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 17:14:57 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:14:58 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:15:13 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:13 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:57 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:57 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:15:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:17:50 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 17:17:50 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'iter_history'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/delfiles.py", line 17, in del_mgs
    async for user_message in client.USER.iter_history(group):
AttributeError: 'NoneType' object has no attribute 'iter_history'
[07-Mar-21 17:17:51 - INFO] - user - @space4renjith  started!
[07-Mar-21 17:18:14 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 17:18:15 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:20:02 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:20:03 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:20:36 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:22:03 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:22:03 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:22:04 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:22:04 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:22:04 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:23:28 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:23:29 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:25:43 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:25:44 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:29:34 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:29:35 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:31:36 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:31:37 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:31:40 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:31:41 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:31:49 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 19:32:40 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:32:41 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:32:45 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:32:46 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:33:01 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 19:33:38 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:33:38 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:33:43 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:33:44 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:33:51 - WARNING] - pyrogram.session.session - [gofilesbot] Sleeping for 3s (required by "messages.SendMedia")
[07-Mar-21 19:34:30 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:34:32 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:36:52 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:36:53 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:44:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:44:58 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:45:08 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:45:09 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:46:12 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:46:13 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:46:17 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:46:19 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:47:14 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:47:14 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:47:16 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:47:20 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:47:21 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:48:01 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:48:02 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:48:03 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:48:07 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:48:08 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:48:18 - ERROR] - pyrogram.dispatcher - 'type' object is not subscriptable
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 46, in query_mgs
    message_ids=int[media.message_id],
TypeError: 'type' object is not subscriptable
[07-Mar-21 19:52:22 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:52:23 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:52:27 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:52:28 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:52:34 - ERROR] - pyrogram.dispatcher - 'int' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 41, in query_mgs
    msg_ids = set(int(x) for x in media.message_id.split())
AttributeError: 'int' object has no attribute 'split'
[07-Mar-21 19:52:49 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:52:50 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:53:46 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:53:47 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:54:33 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:54:34 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:54:54 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:54:55 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:55:55 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:55:56 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:55:59 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:56:00 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:56:02 - ERROR] - pyrogram.dispatcher - local variable 'media' referenced before assignment
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 41, in query_mgs
    print([media.message_id])
UnboundLocalError: local variable 'media' referenced before assignment
[07-Mar-21 19:56:59 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:56:59 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:57:03 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:57:04 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:59:40 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 19:59:41 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 19:59:46 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 19:59:48 - INFO] - user - @space4renjith  started!
[07-Mar-21 19:59:52 - ERROR] - pyrogram.dispatcher - 'int' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 41, in query_mgs
    msg = media.message_id.split()
AttributeError: 'int' object has no attribute 'split'
[07-Mar-21 20:01:49 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:01:51 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:01:56 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:01:58 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:03:26 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:03:27 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:03:32 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:03:33 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:03:37 - ERROR] - pyrogram.dispatcher - 'int' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 42, in query_mgs
    for i in msg[0].split():
AttributeError: 'int' object has no attribute 'split'
[07-Mar-21 20:04:30 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:04:31 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:04:35 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:04:36 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'search_messages'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 24, in query_mgs
    async for messages in client.USER.search_messages(
AttributeError: 'NoneType' object has no attribute 'search_messages'
[07-Mar-21 20:04:37 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:04:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:04:44 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:05:22 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:05:24 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:08:21 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:08:21 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:08:22 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:08:25 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:08:26 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:08:32 - ERROR] - pyrogram.dispatcher - Parameters to generic types must be types. Got 10845.
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 42, in query_mgs
    msg = List[media.message_id]
  File "/usr/lib/python3.6/typing.py", line 682, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.6/typing.py", line 1107, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 1107, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 374, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got 10845.
[07-Mar-21 20:12:36 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:12:37 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:12:40 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:12:41 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:12:47 - ERROR] - pyrogram.dispatcher - append() takes exactly one argument (0 given)
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 42, in query_mgs
    msg = [media.message_id].append()
TypeError: append() takes exactly one argument (0 given)
[07-Mar-21 20:13:26 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:13:27 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:13:31 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:13:32 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:13:59 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:14:00 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:14:43 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:14:45 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:17:33 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:17:34 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:17:38 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:17:40 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:18:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:18:21 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:18:24 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:18:26 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:18:33 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 49, in query_mgs
    revoke=True
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/delete_messages.py", line 66, in delete_messages
    message_ids = list(message_ids) if not isinstance(message_ids, int) else [message_ids]
TypeError: 'NoneType' object is not iterable
[07-Mar-21 20:19:17 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:19:18 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:19:21 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:19:22 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:19:30 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 48, in query_mgs
    message_ids=msg_ids,
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/delete_messages.py", line 66, in delete_messages
    message_ids = list(message_ids) if not isinstance(message_ids, int) else [message_ids]
TypeError: 'NoneType' object is not iterable
[07-Mar-21 20:19:34 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:19:35 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:20:03 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:20:05 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:20:12 - ERROR] - pyrogram.dispatcher - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 49, in query_mgs
    revoke=True
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/delete_messages.py", line 66, in delete_messages
    message_ids = list(message_ids) if not isinstance(message_ids, int) else [message_ids]
TypeError: 'NoneType' object is not iterable
[07-Mar-21 20:20:15 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:20:15 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:26:00 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:26:02 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:27:22 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:27:23 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:27:26 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:27:27 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:35:26 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:35:27 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:35:31 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:35:32 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:38:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:38:45 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:38:54 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:38:55 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:40:08 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:40:08 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:40:28 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:40:28 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'search_messages'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 25, in query_mgs
    async for messages in client.USER.search_messages(
AttributeError: 'NoneType' object has no attribute 'search_messages'
[07-Mar-21 20:40:29 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:40:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:40:43 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:40:46 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:40:47 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:41:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:41:42 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:41:49 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:41:51 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:41:58 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:41:59 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:42:54 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:42:55 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:43:08 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:43:10 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:44:15 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:44:16 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:44:46 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:44:48 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:45:20 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:45:21 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:47:24 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:47:24 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:47:28 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:47:29 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:48:54 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:48:54 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:48:58 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:48:59 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:49:03 - ERROR] - pyrogram.dispatcher - local variable 'media' referenced before assignment
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 43, in query_mgs
    if not media:
UnboundLocalError: local variable 'media' referenced before assignment
[07-Mar-21 20:49:42 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:49:43 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:49:46 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:49:47 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'search_messages'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 25, in query_mgs
    async for messages in client.USER.search_messages(
AttributeError: 'NoneType' object has no attribute 'search_messages'
[07-Mar-21 20:49:47 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:49:50 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:49:51 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:49:54 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:49:55 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:50:20 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:50:22 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:50:50 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:50:51 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:51:07 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:51:08 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:51:21 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:51:22 - INFO] - user - @space4renjith  started!
[07-Mar-21 20:56:53 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:56:53 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 20:56:54 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 20:57:00 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 20:57:01 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:01:02 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:01:03 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:01:06 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:01:07 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:01:28 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:01:32 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:23:08 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:23:09 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:23:18 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 35, in query_mgs
    from_chat_id=messages.from_user.id,
AttributeError: 'NoneType' object has no attribute 'id'
[07-Mar-21 21:24:38 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:24:39 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:24:42 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:24:44 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:24:49 - ERROR] - pyrogram.dispatcher - [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 38, in query_mgs
    reply_to_message_id=message.message_id
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/copy_message.py", line 115, in copy_message
    reply_markup=reply_markup
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/types/messages_and_media/message.py", line 2937, in copy
    caption_entities=caption_entities
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/send_cached_media.py", line 106, in send_cached_media
    **await utils.parse_text_entities(self, caption, parse_mode, caption_entities)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
[07-Mar-21 21:25:17 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:25:18 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:25:23 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:25:24 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:25:28 - ERROR] - pyrogram.dispatcher - [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 37, in query_mgs
    caption=Presets.CAPTION_TEXT
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/copy_message.py", line 115, in copy_message
    reply_markup=reply_markup
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/types/messages_and_media/message.py", line 2937, in copy
    caption_entities=caption_entities
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/send_cached_media.py", line 106, in send_cached_media
    **await utils.parse_text_entities(self, caption, parse_mode, caption_entities)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
[07-Mar-21 21:27:07 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:27:09 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:27:13 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:27:14 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:35:22 - ERROR] - pyrogram.dispatcher - [400 USER_IS_BLOCKED]: The user blocked you (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 37, in query_mgs
    caption=Presets.CAPTION_TEXT
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/copy_message.py", line 115, in copy_message
    reply_markup=reply_markup
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/types/messages_and_media/message.py", line 2937, in copy
    caption_entities=caption_entities
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/send_cached_media.py", line 106, in send_cached_media
    **await utils.parse_text_entities(self, caption, parse_mode, caption_entities)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.UserIsBlocked: [400 USER_IS_BLOCKED]: The user blocked you (caused by "messages.SendMedia")
[07-Mar-21 21:48:15 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:48:17 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:48:35 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:48:37 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:49:46 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:49:47 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:49:50 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:49:51 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:50:11 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:50:12 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:51:01 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:51:03 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:54:43 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:54:43 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:54:46 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:54:48 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:55:59 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:56:00 - INFO] - bot - Bot stopped. Bye.
[07-Mar-21 21:56:03 - INFO] - bot - @pyrofilterbot  started! 
[07-Mar-21 21:56:05 - INFO] - user - @space4renjith  started!
[07-Mar-21 21:58:08 - INFO] - root - Stop signal received (2). Exiting...
[07-Mar-21 21:58:08 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:05:37 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:05:38 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:06:24 - ERROR] - pyrogram.dispatcher - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 34, in query_mgs
    if "recently" in pm_status:
TypeError: argument of type 'NoneType' is not iterable
[08-Mar-21 09:06:59 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:06:59 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:07:01 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:07:02 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:10:45 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:10:46 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:10:51 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:10:51 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:23:43 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:23:43 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:23:47 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:23:47 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:25:24 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:25:25 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:25:28 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:25:29 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:27:29 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:27:30 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:27:34 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:27:35 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:30:44 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:30:45 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:30:55 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:30:55 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:32:09 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:32:10 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:32:22 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:32:22 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:33:46 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:33:48 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:33:52 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:33:52 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:35:41 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:35:42 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:35:44 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:35:45 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:36:13 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:36:14 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:36:17 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:36:17 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:37:13 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:37:14 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:37:16 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:37:16 - INFO] - user - @space4renjith  started!
[08-Mar-21 09:46:09 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 09:46:10 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 09:46:15 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 09:46:15 - INFO] - user - @space4renjith  started!
[08-Mar-21 10:35:41 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 10:35:42 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 10:35:52 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 10:35:52 - INFO] - user - @space4renjith  started!
[08-Mar-21 10:36:22 - WARNING] - pyrogram.session.session - [BQDGRUC0_qw2GVQ2gpLFaXOt0mrWg16cBZPATQvR8KThDzi-NRE1I9DBXO4Zah2UaYDeELOMXnCA3Yn7SHd6xK-Ql7avMxfeo7zwKXMzDZqxIlTx1zP6905eBkqFA172yyBf-j1PVs-Aa6dJIv0-3VqRFUafX4F0LdnRLIiSoP89hVapOX67HqaxpVwt1IXQ6Nr51GEB-bP3hjQ_Is6m-frrSGHWZBuHyom8SAINeKxnnlCKvuL6MuTpy15bOVrw_IpnTF1DZirLNuvgzR7GdlhxFZDLvNhBbRo1NXB2HOpqbvmXt8fBN0aHp21lRCdA6KUJdloPCqf1YGt1lPjLMfAYKoX5RAA] Sleeping for 16s (required by "messages.GetHistory")
[08-Mar-21 10:36:53 - WARNING] - pyrogram.session.session - [BQDGRUC0_qw2GVQ2gpLFaXOt0mrWg16cBZPATQvR8KThDzi-NRE1I9DBXO4Zah2UaYDeELOMXnCA3Yn7SHd6xK-Ql7avMxfeo7zwKXMzDZqxIlTx1zP6905eBkqFA172yyBf-j1PVs-Aa6dJIv0-3VqRFUafX4F0LdnRLIiSoP89hVapOX67HqaxpVwt1IXQ6Nr51GEB-bP3hjQ_Is6m-frrSGHWZBuHyom8SAINeKxnnlCKvuL6MuTpy15bOVrw_IpnTF1DZirLNuvgzR7GdlhxFZDLvNhBbRo1NXB2HOpqbvmXt8fBN0aHp21lRCdA6KUJdloPCqf1YGt1lPjLMfAYKoX5RAA] Sleeping for 16s (required by "messages.GetHistory")
[08-Mar-21 10:43:15 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 10:43:16 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 10:43:21 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 10:43:22 - INFO] - user - @space4renjith  started!
[08-Mar-21 10:51:39 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 10:51:40 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 10:51:42 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 10:51:43 - INFO] - user - @space4renjith  started!
[08-Mar-21 10:53:02 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 10:53:02 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 10:54:52 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 10:54:53 - INFO] - user - @space4renjith  started!
[08-Mar-21 10:54:55 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 10:54:55 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 10:55:07 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 10:55:08 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:01:20 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:01:20 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:01:26 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:01:27 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:02:02 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:02:02 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:02:25 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:02:26 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:03:59 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:03:59 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:04:19 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:04:19 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:08:41 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:08:41 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:08:44 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:08:44 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:10:37 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:10:37 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:12:36 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:12:37 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:23:23 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:23:24 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:25:50 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:25:50 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:26:18 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:26:19 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:26:22 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:26:22 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:26:41 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:26:42 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:26:45 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:26:45 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:27:24 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:27:25 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:27:27 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:27:28 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:28:12 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:28:13 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:28:15 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:28:15 - INFO] - user - @space4renjith  started!
[08-Mar-21 11:28:58 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 11:28:58 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 11:57:14 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 11:57:15 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:10:06 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:10:07 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 12:15:21 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 12:15:22 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:24:06 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:24:06 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 12:24:09 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 12:24:09 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:24:32 - ERROR] - pyrogram.dispatcher - [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 38, in query_mgs
    caption=Presets.CAPTION_TEXT
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/copy_message.py", line 115, in copy_message
    reply_markup=reply_markup
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/types/messages_and_media/message.py", line 2937, in copy
    caption_entities=caption_entities
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/send_cached_media.py", line 106, in send_cached_media
    **await utils.parse_text_entities(self, caption, parse_mode, caption_entities)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
[08-Mar-21 12:35:45 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:35:46 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 12:35:49 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 12:35:49 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:36:53 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:36:53 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 12:36:55 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 12:36:56 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:37:22 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:37:22 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 12:45:39 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 12:45:40 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:46:00 - ERROR] - pyrogram.dispatcher - [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 32, in query_mgs
    action="upload_video"
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/send_chat_action.py", line 100, in send_chat_action
    action=action
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SetTyping")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/renju/0Development/gofilesbot/plugins/gofiles.py", line 52, in query_mgs
    caption=Presets.CAPTION_TEXT
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/copy_message.py", line 115, in copy_message
    reply_markup=reply_markup
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/types/messages_and_media/message.py", line 2937, in copy
    caption_entities=caption_entities
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/messages/send_cached_media.py", line 106, in send_cached_media
    **await utils.parse_text_entities(self, caption, parse_mode, caption_entities)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/methods/advanced/send.py", line 81, in send
    else self.sleep_threshold)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/renju/0Development/gofilesbot/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMedia")
[08-Mar-21 12:48:41 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:48:42 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 12:48:47 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 12:48:47 - INFO] - user - @space4renjith  started!
[08-Mar-21 12:50:13 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 12:50:14 - INFO] - bot - Bot stopped. Bye.
[08-Mar-21 15:03:01 - INFO] - bot - @pyrofilterbot  started! 
[08-Mar-21 15:03:02 - INFO] - user - @space4renjith  started!
[08-Mar-21 15:06:06 - INFO] - root - Stop signal received (2). Exiting...
[08-Mar-21 15:06:07 - INFO] - bot - Bot stopped. Bye.
